version: "2.4"

services:
  postgres:
    image: docker.io/ondrejit/postgres-wal-g:15.2
    build: .
    environment:
#     TZ: Europe/Prague
#     LANG: cs_CZ.UTF-8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: postgres
#     POSTGRES_HOST_AUTH_METHOD: trust
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: XXX
      AWS_SECRET_ACCESS_KEY: YYY
      WALG_PROFILE: dev
#     WALG_PROFILE: restore
      WALG_S3_PREFIX: s3://awesome-backup/postgresql
  pgweb:
    image: docker.io/sosedoff/pgweb:latest
    command: sh -c "sleep 5; /usr/bin/pgweb --bind=0.0.0.0 --listen=8080"
    environment:
      DATABASE_URL: postgres://postgres:passwd@postgres:5432/postgres?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres
